# Generated by Django 5.0 on 2024-01-26 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_client_as_person_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_connect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_client_type',
            },
        ),
        migrations.CreateModel(
            name='MarchantType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_marchant_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=30)),
                ('middle_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.address')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_person',
            },
        ),
        migrations.CreateModel(
            name='Marchant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code_postal', models.CharField(max_length=5)),
                ('site_web', models.URLField()),
                ('born_at', models.DateField()),
                ('is_active', models.BooleanField()),
                ('zip_code', models.CharField(max_length=5)),
                ('society_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('marchant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.marchanttype')),
                ('reference_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.person')),
            ],
            options={
                'db_table': 'op_marchant',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('as_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.person')),
            ],
            options={
                'db_table': 'op_client',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('birth_place', models.TextField(max_length=30)),
                ('born_at', models.DateField()),
                ('hired_at', models.DateField()),
                ('is_available', models.TextField(max_length=34)),
                ('avenue', models.TextField(max_length=20)),
                ('number', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('as_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.person')),
            ],
            options={
                'db_table': 'op_agent',
            },
        ),
    ]
