# Generated by Django 5.0 on 2024-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_agent_id_alter_client_id_alter_clienttype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('A', 'Agent'), ('C', 'Client'), ('M', 'Merchant')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
