# Generated by Django 5.0 on 2024-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
