# Generated by Django 5.0 on 2024-01-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_city',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.city')),
            ],
            options={
                'db_table': 'op_address',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_client_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_country',
            },
        ),
        migrations.CreateModel(
            name='MarchantType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_marchant_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=30)),
                ('middle_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.address')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_person',
            },
        ),
        migrations.CreateModel(
            name='Marchant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code_postal', models.CharField(max_length=5)),
                ('site_web', models.URLField()),
                ('born_at', models.DateField()),
                ('is_active', models.BooleanField()),
                ('zip_code', models.CharField(max_length=5)),
                ('society_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('marchant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.marchanttype')),
                ('reference_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.person')),
            ],
            options={
                'db_table': 'op_marchant',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('as_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.person')),
            ],
            options={
                'db_table': 'op_client',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('birth_place', models.TextField(max_length=30)),
                ('born_at', models.DateField()),
                ('hired_at', models.DateField()),
                ('is_available', models.TextField(max_length=34)),
                ('avenue', models.TextField(max_length=20)),
                ('number', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('as_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.person')),
            ],
            options={
                'db_table': 'op_agent',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.country')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_province',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.province'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.province'),
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.city')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rf_township',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='township',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.township'),
        ),
    ]
