# Generated by Django 5.0 on 2024-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('CategorieId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=2000)),
                ('NomCategorie', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
