# Generated by Django 5.0 on 2024-01-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_created_at_address_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='as_person',
        ),
        migrations.RemoveField(
            model_name='clienttype',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='marchant',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='marchant',
            name='marchant_type',
        ),
        migrations.RemoveField(
            model_name='marchant',
            name='reference_person',
        ),
        migrations.RemoveField(
            model_name='marchanttype',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by_user',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='Marchant',
        ),
        migrations.DeleteModel(
            name='MarchantType',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
