# Generated by Django 5.0 on 2024-01-26 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_client_as_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='acronym',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
