# Generated by Django 5.0 on 2024-01-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_commune_id_address_commune_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='created_by_user_id',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='ville_id',
            new_name='ville',
        ),
    ]
