# Generated by Django 5.0 on 2024-01-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_address_unique_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address',
        ),
    ]
